- name: Prepare machine
  hosts: all
  become: true
  remote_user: root
  pre_tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400 #One day
  vars:
      - pip_install_packages:
            - name: docker
  roles:
      - geerlingguy.pip
