- name: Deploy redmine app
  hosts: all
  become: true
  remote_user: root
  gather_facts: no
  vars:
      - pip_install_packages:
            - name: docker
  tasks:
      - name: Run container
        docker_container:
            name: app
            image: redmine
            auto_remove: yes
            pull: yes
            ports:
                - '3000:3000'
            env:
                REDMINE_DB_POSTGRES: '{{ REDMINE_DB_POSTGRES }}'
                REDMINE_DB_PORT: '{{ REDMINE_DB_PORT }}'
                REDMINE_DB_USERNAME: '{{ REDMINE_DB_USERNAME }}'
                REDMINE_DB_PASSWORD: '{{ REDMINE_DB_PASSWORD }}'
                REDMINE_DB_DATABASE: '{{ REDMINE_DB_DATABASE }}'
            state: started
