- import_playbook: datadog.yml

- name: Deploy test app
  hosts: all
  become: true
  remote_user: root
  vars:
      - pip_install_packages:
            - name: docker

  pre_tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400 #One day

  roles:
      - geerlingguy.pip

  tasks:
      - name: Pull default Docker image
        docker_image:
            name: '{{ app_image }}'
            source: pull

      - name: Run container
        docker_container:
            name: app
            image: redmine
            ports:
                - '3000:3000'
            env:
                REDMINE_DB_POSTGRES: '{{ REDMINE_DB_POSTGRES }}'
                REDMINE_DB_PORT: '{{ REDMINE_DB_PORT }}'
                REDMINE_DB_USERNAME: '{{ REDMINE_DB_USERNAME }}'
                REDMINE_DB_PASSWORD: '{{ REDMINE_DB_PASSWORD }}'
                REDMINE_DB_DATABASE: '{{ REDMINE_DB_DATABASE }}'
            state: started
