- name: Deploy test app
  hosts: all
  become: true
  remote_user: root
  roles:
      - geerlingguy.docker
      - geerlingguy.pip
      - { role: datadog.datadog, become: yes }
  vars_files:
      - group_vars/webservers.yml
      - group_vars/datadog.yml
  vars:
      - pip_install_packages:
            - name: docker

  tasks:
      - name: Pull default Docker image
        docker_image:
            name: '{{ app_image }}'
            source: pull

      - name: Run container
        docker_container:
            name: app
            image: '{{ app_image }}'
            ports:
                - '3000:3000'
            env:
                REDMINE_DB_POSTGRES: '{{ REDMINE_DB_POSTGRES }}'
                REDMINE_DB_PORT: '{{ REDMINE_DB_PORT }}'
                REDMINE_DB_USERNAME: '{{ REDMINE_DB_USERNAME }}'
                REDMINE_DB_PASSWORD: '{{ REDMINE_DB_PASSWORD }}'
                REDMINE_DB_DATABASE: '{{ REDMINE_DB_DATABASE }}'
            state: started
